/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Calculadora.java
 *
 * Created on 26/07/2014, 10:36:15 PM
 */
/**
 *
 * @author Rikardo
 */
public class Calculadora extends javax.swing.JFrame {

    /** Creates new form Calculadora */
    public Calculadora() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Result = new javax.swing.JTextField();
        Siete = new javax.swing.JButton();
        Ocho = new javax.swing.JButton();
        Nueve = new javax.swing.JButton();
        Entre = new javax.swing.JButton();
        Cuatro = new javax.swing.JButton();
        Cinco = new javax.swing.JButton();
        Seis = new javax.swing.JButton();
        Por = new javax.swing.JButton();
        Uno = new javax.swing.JButton();
        Dos = new javax.swing.JButton();
        Tres = new javax.swing.JButton();
        Mas = new javax.swing.JButton();
        Punto = new javax.swing.JButton();
        Cero = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        Menos = new javax.swing.JButton();
        Borra = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        Result.setEditable(false);
        Result.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });
        Result.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultKeyTyped(evt);
            }
        });

        Siete.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Siete.setText("7");
        Siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SieteActionPerformed(evt);
            }
        });

        Ocho.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Ocho.setText("8");
        Ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OchoActionPerformed(evt);
            }
        });

        Nueve.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Nueve.setText("9");
        Nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NueveActionPerformed(evt);
            }
        });

        Entre.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Entre.setText("/");
        Entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreActionPerformed(evt);
            }
        });

        Cuatro.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Cuatro.setText("4");
        Cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuatroActionPerformed(evt);
            }
        });

        Cinco.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Cinco.setText("5");
        Cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CincoActionPerformed(evt);
            }
        });

        Seis.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Seis.setText("6");
        Seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeisActionPerformed(evt);
            }
        });

        Por.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Por.setText("X");
        Por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorActionPerformed(evt);
            }
        });

        Uno.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Uno.setText("1");
        Uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoActionPerformed(evt);
            }
        });

        Dos.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Dos.setText("2");
        Dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosActionPerformed(evt);
            }
        });

        Tres.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Tres.setText("3");
        Tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresActionPerformed(evt);
            }
        });

        Mas.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Mas.setText("+");
        Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasActionPerformed(evt);
            }
        });

        Punto.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Punto.setText(".");
        Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoActionPerformed(evt);
            }
        });

        Cero.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Cero.setText("0");
        Cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeroActionPerformed(evt);
            }
        });

        Igual.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        Menos.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Menos.setText("-");
        Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosActionPerformed(evt);
            }
        });

        Borra.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Borra.setText("<--");
        Borra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorraActionPerformed(evt);
            }
        });

        Limpiar.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Limpiar.setText("C");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Borra, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Result, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Por, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Siete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Entre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Borra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Siete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Por, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void NueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NueveActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"9";
        Result.setText(nre);
        }
}//GEN-LAST:event_NueveActionPerformed

private void OchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OchoActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"8";
        Result.setText(nre);
        }
}//GEN-LAST:event_OchoActionPerformed

private void SieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SieteActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"7";
        Result.setText(nre);
        }
}//GEN-LAST:event_SieteActionPerformed

private void SeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeisActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"6";
        Result.setText(nre);
        }
}//GEN-LAST:event_SeisActionPerformed

private void CincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CincoActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"5";
        Result.setText(nre);
        }
}//GEN-LAST:event_CincoActionPerformed

private void CuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuatroActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"4";
        Result.setText(nre);
        }
}//GEN-LAST:event_CuatroActionPerformed

private void TresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"3";
        Result.setText(nre);
        }
}//GEN-LAST:event_TresActionPerformed

private void DosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"2";
        Result.setText(nre);
        }
}//GEN-LAST:event_DosActionPerformed

private void UnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        String nre=re+"1";
        Result.setText(nre);
        }
}//GEN-LAST:event_UnoActionPerformed

private void CeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeroActionPerformed
    String re=Result.getText();
    if(re.length()<25){
        if(re.length()==1 && re.charAt(0)=='0'){
            Result.setText("0");
        }else{
            String nre=re+"0";
            Result.setText(nre);
        }
    }
}//GEN-LAST:event_CeroActionPerformed

private void PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoActionPerformed
    String re=Result.getText();
    int tam=re.length();
    int band=0;
    for(int i=0;i<tam;i++){
        if(re.charAt(i)=='.'){
          band=1;  
        }
    }
    if(re.length()<25 && band==0){
        if(re.length()==0){
           String nre="0.";
            Result.setText(nre); 
        }else{
            String nre=re+".";
            Result.setText(nre);
            }
    }
}//GEN-LAST:event_PuntoActionPerformed

private void BorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorraActionPerformed
    String valor=Result.getText();
    String nuevo = valor.substring(0, valor.length()-1);
    Result.setText(nuevo);
}//GEN-LAST:event_BorraActionPerformed

private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
    Result.setText("");
}//GEN-LAST:event_LimpiarActionPerformed

private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
   
}//GEN-LAST:event_ResultActionPerformed

private void ResultKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultKeyTyped
  
}//GEN-LAST:event_ResultKeyTyped

private void MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasActionPerformed
    String re=Result.getText();
    int tam=re.length();
    int band=0;
    for(int i=0;i<tam;i++){
        if(re.charAt(i)=='-' || re.charAt(i)=='+' || re.charAt(i)=='x' || re.charAt(i)=='/'){
          band=1;  
        }
    }
    if(re.length()<25 && band==0){
        if(re.length()==0){
           String nre="0+";
            Result.setText(nre); 
        }else{
            String nre=re+"+";
            Result.setText(nre);
            }
    }
}//GEN-LAST:event_MasActionPerformed

private void PorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorActionPerformed
    String re=Result.getText();
    int tam=re.length();
    int band=0;
    for(int i=0;i<tam;i++){
        if(re.charAt(i)=='-' || re.charAt(i)=='+' || re.charAt(i)=='x' || re.charAt(i)=='/'){
          band=1;  
        }
    }
    if(re.length()<25 && band==0){
        if(re.length()==0){
           String nre="0x";
            Result.setText(nre); 
        }else{
            String nre=re+"x";
            Result.setText(nre);
            }
    }
}//GEN-LAST:event_PorActionPerformed

private void EntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreActionPerformed
    String re=Result.getText();
    int tam=re.length();
    int band=0;
    for(int i=0;i<tam;i++){
        if(re.charAt(i)=='-' || re.charAt(i)=='+' || re.charAt(i)=='x' || re.charAt(i)=='/'){
          band=1;  
        }
    }
    if(re.length()<25 && band==0){
        if(re.length()==0){
           String nre="0/";
            Result.setText(nre); 
        }else{
            String nre=re+"/";
            Result.setText(nre);
            }
    }
}//GEN-LAST:event_EntreActionPerformed

private void MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosActionPerformed
    String re=Result.getText();
    int tam=re.length();
    int band=0;
    for(int i=0;i<tam;i++){
        if(re.charAt(i)=='-' || re.charAt(i)=='+' || re.charAt(i)=='x' || re.charAt(i)=='/'){
          band=1;  
        }
    }
    if(re.length()<25 && band==0){
        if(re.length()==0){
           String nre="0-";
            Result.setText(nre); 
        }else{
            String nre=re+"-";
            Result.setText(nre);
            }
    }
}//GEN-LAST:event_MenosActionPerformed

private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
    String op=Result.getText();
    int tam=op.length();
    String num1="";
    String num2="";
    char operando='?';
    int bandop=0;
    try{
    for(int i=0;i<tam;i++){
        if(bandop==0){
            if(op.charAt(i)=='x' || op.charAt(i)=='-' || op.charAt(i)=='+' || op.charAt(i)=='/'){
                bandop=1;
                operando=op.charAt(i);
                }
            else{
                num1=num1+op.charAt(i);
                }
            }
        else{
            num2=num2+op.charAt(i);
            }
        }
    //System.out.println(num1);
    //System.out.println(num2);
    float n1=0,n2=0,res=0;
    n1=Float.parseFloat(num1);
    n2=Float.parseFloat(num2);
    String fin="";
    if(operando=='x'){
        res=n1*n2;
    }
    if(operando=='+'){
        res=n1+n2;
    }
    if(operando=='-'){
        res=n1-n2;
    }
    if(operando=='/'){
        res=n1/n2;
    }
    fin=String.valueOf(res);
    String text="";
    int max=fin.length()-1;
        for(int j=max;j>=0;j--){
            if(fin.charAt(j)=='0' || fin.charAt(j)=='.'){
                if(fin.charAt(j)=='.'){
                    fin=fin.substring(0, fin.length()-1);
                    break;
                }else{
                    fin=fin.substring(0, fin.length()-1);
                }
            }
            else{
                break;
                }
        }
    
    text=fin;
    if(fin.equals("Infinity")){
                text="Indefinido";
            }
   Result.setText(text);
    }
    catch(Exception e){
        System.out.println("Error");
    }
}//GEN-LAST:event_IgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borra;
    private javax.swing.JButton Cero;
    private javax.swing.JButton Cinco;
    private javax.swing.JButton Cuatro;
    private javax.swing.JButton Dos;
    private javax.swing.JButton Entre;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Mas;
    private javax.swing.JButton Menos;
    private javax.swing.JButton Nueve;
    private javax.swing.JButton Ocho;
    private javax.swing.JButton Por;
    private javax.swing.JButton Punto;
    private javax.swing.JTextField Result;
    private javax.swing.JButton Seis;
    private javax.swing.JButton Siete;
    private javax.swing.JButton Tres;
    private javax.swing.JButton Uno;
    // End of variables declaration//GEN-END:variables
}
